# Generated by Django 3.2.7 on 2021-10-09 17:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210927_2232'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dob',
            field=models.DateField(default=datetime.date(2021, 10, 10)),
            preserve_default=False,
        ),
    ]
